kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader
rules:
- apiGroups: [""]
  # add resources as required
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - rolebindings
  - clusterrolebindings
  verbs:
  - get
  - watch
  - list
