{{- define "roleName" }}
{{- printf "\"%s-cluster-reader\"" .Values.name -}}
{{- end }}
{{- define "userNames" }}
{{- printf "\"system:serviceaccount:%s:%s\"" .Values.namespace .Values.name -}}
{{- end }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "roleName" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
roleRef:
  kind: ClusterRole
  name: cluster-reader
subjects:
-
  kind: ServiceAccount
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
userNames:
- {{ template "userNames" . }}
