kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | quote }}
    spec:
      serviceAccountname: {{ .Values.name | quote }}
      serviceAccount: {{ .Values.name | quote }}
      containers:
      - name: {{ .Values.name | quote }}
        image: gerald1248/k8s-cluster-tests
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
        - name: POD_NAMESPACE
          value: {{ .Values.namespace | quote }}
        volumeMounts:
        - name: "{{ .Values.name }}-volume"
          mountPath: /etc/k8s-cluster-tests.d
      volumes:
      - name: "{{ .Values.name }}-volume"
        configMap:
          name: {{ .Values.name | quote }}
