kind: LimitRange
apiVersion: v1
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  limits:
  -
    type: Container
    default:
      cpu: 400m
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 512Mi
